import { Request, Response } from 'express';
import Component from '../models/Component';
import { executeVendorScrape, ScrapeVendorInputSchema } from '../services/scrapeVendor';

export const getComponents = async (req: Request, res: Response): Promise<void> => {
  try {
    const components = await Component.find().sort({ createdAt: -1 });
    res.status(200).json({ 
      success: true, 
      count: components.length, 
      data: components 
    });
  } catch (error: any) {
    res.status(500).json({ 
      success: false, 
      message: 'Server error while fetching components', 
      error: error.message 
    });
  }
};

export const getComponentById = async (req: Request, res: Response): Promise<void> => {
  try {
    const component = await Component.findById(req.params.id);
    if (!component) {
      res.status(404).json({ success: false, message: 'Hardware component not found' });
      return;
    }
    res.status(200).json({ success: true, data: component });
  } catch (error: any) {
    res.status(500).json({ 
      success: false, 
      message: 'Error fetching component details', 
      error: error.message 
    });
  }
};

export const createComponent = async (req: Request, res: Response): Promise<void> => {
  try {
    const newComponent = await Component.create(req.body);
    res.status(201).json({ 
      success: true, 
      data: newComponent 
    });
  } catch (error: any) {
    res.status(400).json({ 
      success: false, 
      message: 'Failed to create component', 
      error: error.message 
    });
  }
};

/**
 * 1000x Programmatic SEO Content Engine
 * Generates massive long-form technical tutorials, C++ code, and FAQs automatically
 */
function generateEngineeringArticle(name: string, vendor: string, specs: Record<string, any>) {
  const voltage = specs['operatingVoltage'] || specs['Voltage'] || '3.3V / 5V Logic';
  const clock = specs['clockSpeed'] || specs['Frequency'] || 'Standard High-Speed Clock';
  const comms = specs['interface'] || specs['Protocol'] || 'I2C / SPI / UART / GPIO';
  
  // Generate clean C++/Arduino boilerplate code for the developer blog
  const sampleCode = `// Autogenerated Boilerplate for ${name}
#include <Arduino.h>
#include <Wire.h>

#define MODULE_POWER_PIN 33
#define STATUS_LED_PIN 2

void setup() {
  Serial.begin(115200);
  while (!Serial) { delay(10); } // Wait for serial console
  
  Serial.println("⚡ PinoutHQ Engine: Initializing ${name}...");
  
  pinMode(MODULE_POWER_PIN, OUTPUT);
  pinMode(STATUS_LED_PIN, OUTPUT);
  
  // Power sequence stabilization delay
  digitalWrite(MODULE_POWER_PIN, HIGH);
  delay(250); 
  
  // Initialize I2C/SPI Data Bus
  Wire.begin();
  Serial.println("✅ Data bus locked. Hardware active at ${voltage}.");
}

void loop() {
  // Main telemetry & polling loop
  digitalWrite(STATUS_LED_PIN, HIGH);
  delay(50);
  digitalWrite(STATUS_LED_PIN, LOW);
  
  // Add your custom firmware processing here
  delay(2000);
}`;

  return {
    title: `Complete Engineering Guide, Wiring Schematics & Pinout for ${name}`,
    metaDescription: `Detailed hardware specification, pinout mapping, power rail requirements, and C++ Arduino firmware boilerplate for the ${name} by ${vendor}.`,
    
    architectureOverview: `The ${name} designed by ${vendor} stands out as a critical building block in modern embedded systems, IoT architecture, and high-reliability edge computing. Designed to operate efficiently within a ${voltage} power envelope, this hardware module provides superior noise immunity and signal integrity. Whether you are designing an industrial telemetry gateway, a remote autonomous sensor node, or a custom consumer electronics PCB, understanding the physical layer characteristics of the ${name} is vital for long-term deployment stability.`,
    
    pinoutAndInterface: `Interfacing with the ${name} requires strict adherence to its bus protocol specifications. Utilizing ${comms} communication protocols, the module allows high-speed throughput while minimizing GPIO pin overhead on your master microcontroller. When mapping your printed circuit board (PCB) traces, ensure that high-frequency clock lines (${clock}) are routed away from sensitive analog reference lines to prevent capacitive coupling and cross-talk. For multi-drop bus topologies, external pull-up resistors (typically 4.7kΩ for I2C buses) are mandatory to maintain sharp digital rising edges across extended line distances.`,
    
    powerAndThermal: `A frequent point of failure in prototyping is improper power rail regulation. The ${name} is engineered for ${voltage} operation. If your master microcontroller operates at 5V logic while this module expects 3.3V, you MUST implement bi-directional logic level converters on all data lines. Applying 5V directly to a 3.3V tolerant pin will cause catastrophic gate oxide breakdown within the silicon. Furthermore, during high-load wireless transmission or rapid sensor polling, peak current draw can spike significantly. We strongly advise placing a 10µF electrolytic decoupling capacitor in parallel with a 0.1µF ceramic capacitor directly across the VCC and GND pins, as close to the physical module header as possible.`,
    
    firmwareCode: sampleCode,
    
    troubleshooting: [
      {
        problem: "Brownout Reset / Intermittent Rebooting",
        cause: "Voltage drops below the minimum operating threshold during peak current spikes.",
        solution: "Add a 100µF low-ESR bulk capacitor across VCC and GND near the module feed and use a dedicated power supply rather than drawing current directly from a PC USB port."
      },
      {
        problem: "Garbage Serial Output / Communication Timeout",
        cause: "Baud rate mismatch or floating data bus lines without adequate pull-up resistors.",
        solution: "Verify your serial console is locked to 115200 baud and confirm 4.7kΩ pull-up resistors are installed on SDA/SCL lines."
      },
      {
        problem: "Overheating or High Standby Current",
        cause: "Latch-up condition caused by applying voltage to GPIO pins before powering VCC.",
        solution: "Ensure your firmware powers the module VCC rail at least 100ms before initializing digital communication pins."
      }
    ],
    
    faqs: [
      {
        question: `What is the operating voltage of the ${name}?`,
        answer: `The ${name} by ${vendor} is designed primarily for ${voltage} operation. Always check the individual datasheet matrix before connecting high-voltage logic rails.`
      },
      {
        question: `Can I use the ${name} with Arduino or ESP32?`,
        answer: `Yes! The module communicates over standard ${comms} protocols, making it 100% compatible with Arduino, ESP32, Raspberry Pi, and STM32 microcontrollers using standard hardware libraries.`
      },
      {
        question: `Where is the best place to buy authentic ${name} stock?`,
        answer: `Due to counterfeit hardware circulating on open marketplaces, we recommend sourcing directly from verified distributors. Use our real-time stock routing button above to lock in authentic inventory at guaranteed market rates.`
      }
    ]
  };
}

export const scrapeAndSaveComponent = async (req: Request, res: Response): Promise<void> => {
  try {
    const validation = ScrapeVendorInputSchema.safeParse(req.body);
    if (!validation.success) {
      res.status(400).json({ 
        success: false, 
        message: 'Invalid scraping parameters provided',
        errors: validation.error.format() 
      });
      return;
    }

    const params = validation.data;
    console.log(`⚡ Initializing autonomous scrape for vendor: [${params.vendorName}] at ${params.url}`);
    
    const scrapeResult = await executeVendorScrape(params);

    if (!scrapeResult.success) {
      res.status(502).json({ 
        success: false, 
        message: 'Scraper failed to extract data from vendor website', 
        error: scrapeResult.error,
        executionTimeMs: scrapeResult.executionTimeMs
      });
      return;
    }

    const componentName = scrapeResult.extractedTitle || `Scraped Hardware (${params.vendorName})`;
    
    // Generate the 1000x SEO masterclass article
    const generatedSeoArticle = generateEngineeringArticle(
      componentName, 
      params.vendorName, 
      scrapeResult.rawSpecifications
    );

    const componentData = {
      name: componentName,
      category: 'Scraped Hardware Module',
      vendor: params.vendorName,
      pinCount: 0,
      specifications: {
        ...scrapeResult.rawSpecifications,
        sourceUrl: params.url,
        scrapedPrice: scrapeResult.price,
        currency: scrapeResult.currency,
        lastScrapedAt: new Date().toISOString(),
        seoArticle: generatedSeoArticle
      },
      inStock: scrapeResult.inStock
    };

    const savedComponent = await Component.findOneAndUpdate(
      { vendor: params.vendorName, name: componentName },
      componentData,
      { new: true, upsert: true }
    );

    console.log(`✅ Successfully synced [${componentName}] with 1000x SEO masterclass to MongoDB Atlas!`);

    res.status(200).json({
      success: true,
      message: 'Successfully scraped vendor and synced hardware specs with MongoDB',
      executionTimeMs: scrapeResult.executionTimeMs,
      data: savedComponent
    });

  } catch (error: any) {
    console.error('🔥 Fatal error during autonomous scraping pipeline:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Server error during scrape pipeline', 
      error: error.message 
    });
  }
};